name: my workflow
on: push

jobs:
  name-of-job:
    runs-on: ubuntu:latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Hello world
        run: |
          echo "Hello World"
